### ISSUE TITLE
:memo: コンペ概要：NFL Helmet Assignment - Getting Started Guide

### ISSUE THREAD

**Issue by ryryrymyg** [ryryrymyg/kaggle_ell#1]
# NFL Helmet Assignment - Getting Started Guide
[https://www.kaggle.com/robikscube/nfl-helmet-assignment-getting-started-guide/notebook](url)
今回のコンペにおけるイントロである上記記事について要点をまとめる。

## Timeline
August 10, 2021 - Start Date.
October 26, 2021 - Entry Deadline. You must accept the competition rules before this date in order to compete.
October 26, 2021 - Team Merger Deadline. This is the last day participants may join or merge teams.
November 2, 2021 - Final Submission Deadline.**

## 本コンペにおける目的、及び方針
- 目的：各ヘルメットを関連する選手に正しく当てはめること
- 方針：ビデオ映像とNext Gen Stats(NGS)トラッキングデータを活用する
### より詳細な目的
ビデオの全フレームで全てのヘルメットのヘルメットボックスを正しく識別し、そのヘルメットに正しいプレイヤーラベルを割り当てること。
## スコアリングの仕組み
- 採点方式：Weighted Accuracy
検出された衝撃のあるヘルメットは衝撃のないヘルメットに比べて1000倍の重みづけがされる。
## Submit 時の制限
+ 検出したボックスと正しい位置のIntersection over Union (IoU)が0.35以上であること
IoUの説明[https://mathwords.net/iou](url)
+ 各フレームで最も高いIoUを持つボックスのペアのみが採点対象となる
+ 各フレームあたりのヘルメット検出予測数は22個以下。
サイドラインの向こう側にいる選手に照準があってしまう場合があるが、それはカウントしてはいけない。サイドラインの向こう側にいる選手には「H00」「V00」のラベルが貼られるため、その選手は無視しなければならない
+ ヘルメットボックスの検出は角フレームで一度だけ
+ 検出されたヘルメットボックスはフレームごとに一位でなくてはならない
フレームごとに同一のボックスは存在しない
> - check_submission関数は提出されたものが上記要件を満たしているかどうかの確認に利用できる。ソースコードは本項では割愛する。
> - NFLImpactScorer関数は予測値に対してスコアの近似値を与えてくれる。ソースコードは本項では割愛する。
## 提供されるデータについて
提供されているデータについて、詳細は以下のページを参照のこと。
[https://www.kaggle.com/c/nfl-health-and-safety-helmet-assignment/data](url)
本項では提供データの概要と利用例を示す。
- /train/ と /test/ フォルダーには，ラベル付けされる動画の mp4 ファイルが入っている
- train_labels.csv - このファイルはトレーニングデータセットでのみ利用可能で、120のトレーニングビデオの正しいヘルメットボックスの位置を提供する
- train_player_tracking.csv と test_player_tracking.csv には、プレイ中にフィールド上にいたすべてのプレイヤーのトラッキングデータが格納されている。
- train_baseline_helmets.csvとtest_baseline_helmets.csvには，ヘルメットボックスの不完全な予測値が格納されている。(例示？)
- images/フォルダとimage_labels.csvには、動画のランダムなフレームのヘルメットボックスが含まれている。これらの画像は、*_baseline_helmets.csvファイルを生成するモデルの学習に使用されたものである。これらの画像を使って独自のヘルメット検出モデルを学習することができる。

## NGSトラッキングデータ
NGSトラッキングデータは選手の動きをフレームごとに示したデータ。ビデオ映像とこのデータをリンクさせることで正しくラベル付を行うことができる。位置以外のパラメータもあるため、これを活用することも可能。
### NGSデータとカメラの向きは一致しないため注意が必要
> NGSデータとビデオ映像の同期を試みる際には、提供されているadd_track_features関数を用いることができる。ソースコードは割愛

## テスト提出データの作成
テスト提出データを作成

**Comment by agatsssssma** [comment]
次までの宿題　以下のnoteを各自読み込みと理解
https://www.kaggle.com/jianghanhan/tuning-deepsort-helmet-mapping-high-score


Timeline 

August 10, 2021 - Start Date.

October 26, 2021 - Entry Deadline. You must accept the competition rules before this date in order to compete.

October 26, 2021 - Team Merger Deadline. This is the last day participants may join or merge teams.

November 2, 2021 - Final Submission Deadline.**
