### ISSUE TITLE
🗣【discussion】Very few studies on Helmet Detection and Collisions

### ISSUE THREAD

**Issue by agatsssssma** [ryryrymyg/kaggle_ell#12]
# Very few studies on Helmet Detection and Collisions
https://www.kaggle.com/c/nfl-health-and-safety-helmet-assignment/discussion/264222
## Outline

ヘルメット検知＆衝突検知に関する既存研究を３つ発見した。

- [An improved helmet detection method for YOLOv3 on an unbalanced dataset](https://arxiv.org/abs/2011.04214)
- [Secure Aerial Surveillance using Split Learning](https://arxiv.org/abs/2107.08628)
- [Helmet detection error analysis in football videos using Amazon SageMaker](https://aws.amazon.com/blogs/machine-learning/helmet-detection-error-analysis-in-football-videos-using-amazon-sagemaker/)

## Comments
- 既存研究少ないらしい。
- 衝突に関するdiscussionも見たところほぼ無い。というかdiscussion自体が活発じゃない 全部合わせて5ページ(100件くらい)しかない、、、

※随時内容更新します。

**Comment by ryryrymyg** [comment]
# ヘルメットの衝撃に関する前回コンペの上位(1位から10位)の結果をまとめたディスカッション
[https://www.kaggle.com/c/nfl-health-and-safety-helmet-assignment/discussion/263991](url)
1位のディスカッションだけ見ると、加速度から衝撃の検出はできていないようである。(カメラの移動に伴う選手の見掛け上の高速移動が考慮されていないため)。ただし重要なパラメータであることは示唆している。
また、前回と今回の差異として、今回のコンペは[test/train]_baseline_helmets.csv(事前に学習したヘルメット検出モデルによる、ベースラインbbox)が提供されているのに対し、前回のコンペではヘルメット検出モデルから作成する必要があった。
