### ISSUE TITLE
🗣【discussion】1st Place Solution (NFL Health & Safety - Helmet Assignment)

### ISSUE THREAD

**Issue by ryryrymyg** [ryryrymyg/kaggle_ell#24]
# 1st Place Solution
https://www.kaggle.com/c/nfl-health-and-safety-helmet-assignment/discussion/284975
1位の人の解法。日本人。
twitter: https://twitter.com/Kmat67916008
ノートブックも公開してくれている。TensorFlow。
https://www.kaggle.com/kmat2019/nfl-1stplace-inference
## Outline
パイプラインは以下の5つ。この要件を満たした4つのモデルを作り、最後にアンサンブルする
- ヘルメット検出器
  - 検出器を2段構えにしている
    - 1つ目でヘルメットの平均サイズを測って、画像サイズを変更する（検出されたヘルメットサイズの平均が25x25になるようにしている）
    - 2つ目でサイズが変更された画像かヘルメットを検出する(同サイズのヘルメットを検出するのに特化した検出器？)
- ムービーの画像を2Dマップ（鳥瞰図）に投影するコンバータ（★これが一番すごい気がする。というか何してるかわからん）
  - CNN(U-Net base)を用いたコンバータ
  - カメラの位置から2Dマップを予想する
  - ヘルメットのバウンディングボックスに注目することで精度が上がるらしい
- プレーヤーを2つのチーム（H/V）に分類する分類器
  - CNN分類器でチームを分ける
- 検出された選手を2Dマップ上に登録し、トラッキングデータと照合する
  - 画像(動画)から作成された選手の位置と、与えられたトラッキングデータをフィッティングする
  - 拡大、回転、xy translation、ratioをICP(Iterative Closest Points)ベースのアルゴリズムで導き出す。
  - これに関しては図を見るほうが早い
- トラッキング
  - トラッキング手法はシンプルに前フレームとのIoUを測るものを使用している。
  - 他の手法も試したが、大きな変化はなかったようである。
- 上記条件を満たす4つのモデルを構築し、ハンガリアン法で最適な場所を割り当てる。
  - ハンガリアン法(https://qiita.com/m__k/items/8e2cb9067ec5d720c30d) 

一般的解法(ヘルメットごとにラベル付けしてトラッキング)と大きく異なる点は、検出された選手の登録と、2Dマップへのマッピング部分。ヘルメットの検出と配置だけで0.8くらい成果が出てた。

## Comments
このISSUEで見て終わらずに、ディスカッションとノートブックを直接見たほうが良い感じ。
図がかなりわかりやすい印象だった。時間はかかると思うけれど、頭からコードを眺めて理解できればかなり力が付きそう。

**Comment by agatsssssma** [comment]
11/21打ち合わせ時のノート

decoderの構成
![decoder](https://user-images.githubusercontent.com/27982677/142833357-738ced0b-5e0b-4a5a-b550-851ec4245335.jpg)
