### ISSUE TITLE
🔥 code『Tuning DeepSort + Helmet Mapping_high_score』調査

### ISSUE THREAD

**Issue by TaikiYamada123** [ryryrymyg/kaggle_ell#3]
# code『[Tuning DeepSort + Helmet Mapping_high_score](https://www.kaggle.com/jianghanhan/tuning-deepsort-helmet-mapping-high-score)』調査
## Outline
kaggleの最もscoreが高いcode調査
## Hypothesis
方針決め、knowledge共有

**Comment by ryryrymyg** [comment]
## 改善点
ノートブック曰く、deepsortのラベルを元のヘルメットボックスにマージするのはとても雑な方法で行われているらしい。
ここが改善できれば精度が上がる可能性あり。
ただしやり方はまだわからん
