### ISSUE TITLE
📝コンペ概要：TensorFlow - Help Protect the Great Barrier Reef

### ISSUE THREAD

**Issue by agatsssssma** [ryryrymyg/kaggle_ell#36]
# url
https://www.kaggle.com/c/tensorflow-great-barrier-reef

# Deadline
February 14, 2022 - Final Submission Deadline.

**Comment by agatsssssma** [comment]
F2（再現率重視）：5Precision×Recall / 4Precision+Recall
https://tech.ledge.co.jp/entry/metrics

**Comment by ryryrymyg** [comment]
# データについて
- https://www.kaggle.com/c/tensorflow-great-barrier-reef/data
API仕様の理解が必要

## ファイルの種別
### train/ 
- video_{video_id}/{video_frame_number}.jpg 
上記形式でトレーニングセット写真が格納されているフォルダ．

### [train/test].csv
 - 画像のメタデータ。他のテストファイルと同様に、テストのメタデータデータのほとんどは、送信時にノートブックでのみ利用可能。ダウンロードできるのは最初の数行だけ。
#### [train/test].csv内のカラム説明
- video_id - 画像が含まれていたビデオのID番号。ビデオのIDは意味のある順序ではない。
- video_frame - ビデオ内での画像のフレーム番号。ダイバーが浮上した時からフレーム番号に時々ギャップがあることが予想される。
- sequence - 指定されたビデオのギャップのないサブセットのID。シーケンスIDは、意味のある順序ではない。
- sequence_frame - 指定されたシーケンス内のフレーム番号
- image_id - '{video_id}-{video_frame}'という形式の，画像のIDコード
- annotations - 文字列形式でヒトデ検出のバウンディングボックスを表したもの。 **提出する予測値と同じフォーマットではない。** test.csvでは利用できない。bボックスは、画像内の左上隅のピクセル座標(x_min, y_min)と、ピクセル単位のwidthとheightで記述される。
- example_sample_submission.csv - 正しいフォーマットのサンプル投稿ファイル。実際の提出物のサンプルはAPIで提供される。これは、予測の適切なフォーマットを説明するためにのみ提供されています。投稿フォーマットについては、[evaluation](https://www.kaggle.com/c/tensorflow-great-barrier-reef/overview/evaluation)で詳しく説明してる。

- example_test.npy - サンプルAPIで提供されるサンプルデータ。

- greatbarrierreef - テストセットのピクセル配列を提供する画像配信API。サンプルをオフラインでエラーなく実行するには、Python 3.7とLinux環境が必要になる場合がある。

## Time-series API Details(時系列API?)
APIでは、ビデオとフレーム番号の順に、画像を1枚ずつピクセル配列として提供している。

テストセットには約13,000枚の画像が含まれている。

APIは、初期化後に約2GBのメモリを必要とする。初期化ステップ（env.iter_test()）では、それ以上のメモリを必要とする。この呼び出しを行うまでは、モデルをロードしないほうが良い。また、データの読み込みと提供に必要なランタイムは、10分未満

**Comment by ryryrymyg** [comment]
# 提出フォーマット
投稿フォーマットでは、スペースで区切られたバウンディングボックスのセットが必要です。例えば、以下のようになります。
> 0.5 0 0 100 100
は、画像に信頼度0.5のバウンディングボックスがあり、x == 0、y == 0で、幅と高さが100であることを示しています。
> 0.3 0 0 50 50 0.5 10 10 30 30
と入力すると、画像の中に2つのバウンディングボックスがあると予測されます。各予測の行には、画像のすべてのバウンディングボックスを含める必要があります。
