### ISSUE TITLE
🗣【discussion】Detection model ensembling

### ISSUE THREAD

**Issue by agatsssssma** [ryryrymyg/kaggle_ell#6]
# Detection model ensembling
## Outline
- 複数のyolo v5モデルをアンサンブルした結果をdeepsortに投げ込めない。
  - 2021/9/22 に yoro v5_deepsort_pytorch でアンサンブル機能実装
  https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/177

※ 筆者の処理パイプライン YoloV5 -> DeepSort -> Point Set Registration -> Point Set Matching

## Comments
- 最近アンサンブル機能が付いた。いち早くここのアンサンブルやれば差がつけられる？
- アンサンブルなんかよりまずアルゴリズム勉強からですけどね、、、(9/30現在)

**Comment by tymd34711** [comment]
deepsortのアンサンブルを実装したがあまり効果なし(yolov5s, yolov5m)。
notebookファイルは[こちら](https://github.com/ryryrymyg/kaggle_ell/blob/main/deepsort_ensamble.ipynb)(クソ雑コードですがご容赦ください)。
