### ISSUE TITLE
📝NBME 1st place solution

### ISSUE THREAD

**Issue by ryryrymyg** [ryryrymyg/kaggle_ell#72]
# NBME 1st place solution
- Code
https://www.kaggle.com/code/currypurin/nbme-final-submit-currypurin/notebook
- Discussion
https://www.kaggle.com/competitions/nbme-score-clinical-patient-notes/discussion/323095
- Key words
  - MLM(Masked Language Model)
  - pseudo labeling
  - AWP(何かわからん)
  - GroupStratifiedKFolds
  - オーグメンテーション

## Outline
NBMEコンペ1位の解法
![image](https://user-images.githubusercontent.com/41929553/167902668-63f5e53c-37e5-4e0f-96b7-10567274bf48.png)

図1 NBME 1st place solution Pipeline

- 使ったモデル
  - deberta-v3-large
  - deberta-v2-xlarge
  - deberta-large
これらのモデルは時間の都合上使った

- pseudo labeling
  - 疑似ラベリングに使用するデータはいろいろやったけど、結局データセット全体からランダムにサンプリングすることでcv.が改善された。

- オーグメンテーション
  - PNから１文除去する
  - 2割増やす
  - CVはほとんど変わらなかったが、このタスクとデータに有用と判断し採用
  - 疑似ラベルデータにオーグメンテーションは適用しなかった

- Auxilliary Target Learning
  - 以下の3つのチャネルを用意し、全てのチャネルから学習した
    - channel_0: Normal target
    - channel_1: start: 1, else: 0
    - channel_2: end: 1, else: 0
  - CVの向上はわずかだったが擬似ラベルを使ったensemble(blend)に使用でき、実際PrivateLBで効いた

- 後処理
  - 前後のスペースを削除
  - [Be aware of white space [DeBERTa+RoBERTa]](https://www.kaggle.com/code/junkoda/be-aware-of-white-space-deberta-roberta)

- Fold
  - 途中まで5Foldを使ってたけど、途中から10FoldからGroupStratifiedKFoldsに変えたのが一番良かった。

## Comments
  - pseudo labelingの実装は少なくとも読んでおきたい。
  - GroupStatifiedKFoldsを調べる
  - AWPってなんだ
    - コード載せてくれてるから読めばわかるか。。。？

**Comment by agatsssssma** [comment]
AWPはこれっぽいですね
https://github.com/csdongxian/AWP

**Comment by agatsssssma** [comment]
https://zenn.dev/ycarbon/articles/6b26cc19ff33f5
