### ISSUE TITLE
🔥Deberta single model

### ISSUE THREAD

**Issue by ryryrymyg** [ryryrymyg/kaggle_ell#77]
# Deberta single model
## Outline
Debertaのモデルを回した結果を入れていく
## Hypothesis
うまいこと設定できればDeberta-v3-largeシングルモデルで
- CV: 0.87
- LB: 0.842
を達成できるはず

**Comment by ryryrymyg** [comment]
## Deberta-large
以下の条件でkaggle kernelで学習しようとしたが失敗した。
- model: deberta-large
- scheduler: cosine
- epochs: 4
- trn_fold: [0, 1, 2, 3]
Foldの分布の比率を整える基準: スコア

失敗原因
- CUDA out of memory. Tried to allocate 502.00 MiB (GPU 0; 15.90 GiB total capacity; 14.37 GiB already allocated; 11.75 MiB free; 15.02 GiB reserved in total by PyTorch)

**Comment by agatsssssma** [comment]
## Deberta-v3-large

model: deberta-v3-large
epochs: 4
trn_fold: [0, 1, 2, 3, 4] (5fold)
batch_size: 16

CV: 0.8614
LB: 0.8362

## comment

- baselineのfoldを5にしてみただけ
- LB scoreは fold4の時から0.003のみ上昇
- 学習時間：8時間半 (39437.9s)

**Comment by ryryrymyg** [comment]
## Deberta-v3-base
model: deberta-v3-large
epochs: 10
trn_fold: [0, 1, 2, 3, 4] (5fold)
batch_size: 8

CV: 0.8530
LB: 0.8194

## comment

- Debarta-v3-baseのepoch数を5->10に増やしたもの
- LB scoreは5epochのLB(0.8212)に比べ小さかった
- CV scoreも多少落ちている
- epoch増やしても精度上がらず。baseのモデルは最初に提出したものを使っていくこととする
