### ISSUE TITLE
🗣【discussion】Patent CPC Title Dataset

### ISSUE THREAD

**Issue by agatsssssma** [ryryrymyg/kaggle_ell#81]
https://www.kaggle.com/competitions/us-patent-phrase-to-phrase-matching/discussion/328513
## Outline
CPC分類のタイトル＋対応する特許明細書のアブスト？のデータセットを作成。

## Comments

- データセットのカラムと内容抜粋
-https://www.kaggle.com/datasets/grimmace/sampled-patent-titles
![スクリーンショット 2022-06-04 202652](https://user-images.githubusercontent.com/27982677/171997001-6e7e3cbb-1121-4753-876a-4c3c8381cd90.png)

- データセット中の全CPCのうち半数にはなぜかアブストが入っていない。とはいえ[baseline](https://www.kaggle.com/code/yasufuminakama/pppm-deberta-v3-large-baseline-w-w-b-train)ではタイトルまでしか学習データに入れていないため、アブストまで学習に使えば精度向上するかも？

**Comment by agatsssssma** [comment]
以下メモ

- CPCにダブりはない。しかし、公式が共有しているtrain.csvではCPCのうち頭３桁（「H04」など）までしか記載無く、この点学習時どうするか要検討。

**Comment by agatsssssma** [comment]
> 公式が共有しているtrain.csvではCPCのうち頭３桁（「H04」など）までしか記載無く、この点学習時どうするか要検討。
とりあえずtrain.csvのcpcに対応するabstractの中から１つランダムに抜き出し、train.csvに結合して学習させてみる。
CVせずにテスト学習中。

**Comment by agatsssssma** [comment]
>CVせずにテスト学習中。


上記学習がメモリエラー。
batchsize 16 -> 4に落としても駄目。
現在1にして学習中。ダメならkaggle note bookより強い環境使わないと学習できない可能性大。

**Comment by agatsssssma** [comment]
batch size 1でもメモリエラー
kaggle note book環境ではこのアブストデータをくっつけて学習するの厳しそう。

**Comment by TaikiYamada123** [comment]
Deberta-v3-large StratifiedGroupKFold
https://www.kaggle.com/code/tymd34711/pppm-deberta-v3-large-baseline-w-w-b-train/edit/run/97454652
