### ISSUE TITLE
📝DFL - Bundesliga Data Shootout Outline

### ISSUE THREAD

**Issue by ryryrymyg** [ryryrymyg/kaggle_ell#93]
# DFL - Bundesliga Data Shootout
## Outline
[DFL - Bundesliga Data Shootout](https://www.kaggle.com/competitions/dfl-bundesliga-data-shootout/overview) の概要
## Comments
ツリーに情報をぶら下げてください

**Comment by agatsssssma** [comment]
EDA
https://www.kaggle.com/code/ihelon/bundesliga-data-shootout-eda

**Comment by agatsssssma** [comment]
baseline code
efficent netを用いたもの
https://www.kaggle.com/code/its7171/dfl-benchmark-training

**Comment by ryryrymyg** [comment]
## イベントの種類について
[Event Description](https://www.kaggle.com/competitions/dfl-bundesliga-data-shootout/overview/event-descriptions)
### Play
playとは、プレーヤーがボールコントロールを他のチームのメンバーに切り替えることを言う。
プレイイベントは、passまたはcrossとして実行される。
  - Cross
PlayがCrossであるか否かはPlayを行うプレーヤーとそれを受ける可能性のあるプレーヤーの位置によって決まる。クロスを行うプレイヤーは、4つのクロスゾーン(添付画像の濃い赤色領域)のうちの1つのおおよそ内側にいなければならない。
クロスの受け手の可能性があるのは、およそペナルティエリア(添付画像の薄い赤色領域)の内側でなければならない。
  - Pass
Passは、クロスの定義を満たさない他のチームメンバーへボールコントロールを変更する試みと定義される。
> その他細かなルール：
クロスの条件
　プレーされたボールの距離は中距離（10メートルから30メートル）または長距離（30メートル以上）でなければならず、プレーされたボールの高さは高くなければならない（膝の高さより上にプレーされなければならない）。
　プレーしたボールが相手選手にブロックされた場合にクロスに分類するためには、実際にプレーした高さや移動距離ではなく、意図した高さや距離が決め手となる。(ここは判別つけるのが難しい気がする)

![image](https://user-images.githubusercontent.com/41929553/185775529-698c78af-f4e1-4634-9045-ca26556b5415.png)

さらに、すべてのPlayアクション（パスとクロスの両方）は、オープンプレー、コーナーキック、またはフリーキックとして実行される。
- コーナーキック
コーナーキックとは、防御側プレーヤーのタッチによりボールがゴールラインを越えた後、ゲームを再開するためにプレーを実行することをいう。
- フリーキック
フリーキックとは、ルール違反によりレフリーが試合を止めた後、 ゲームを再開するために行うプレーである。
- オープンプレー
オープンプレーとは、インプレーで行われ、デッドボールの状況（コーナーキック、フリーキック、その他のセットピースなど）ではないプレーのことである。

### Throw-ins
Throw-inとは、相手チームのタッチの後、ボールが*サイドライン*を越えてアウトオブプレーになった後、ゲームを再開することをいう。

### Challenges
チャレンジとは、ディフェンスがオフェンス(ボール保持者)のボールを奪いに行く、もしくはファールをとってプレーを止めることを言う。直訳は以下。
> 相手チームの2人のプレーヤーが、物理的にボールコントロールを得るか受け ることが可能であり、それを試みるプレーヤーのアクションである。チャレンジは、2人のプレーヤーのうち1人がボールに触れるか、相手側プレーヤーをファウルすることを要求する。

次のような場合に区別される。
- Opponent rounded
　ディフェンスがボールをコントロールしているプレイヤーからボールを奪取しに行く行為。
　ボールコントロールをしているプレイヤーは、チャレンジの後、相手側プレイ ヤーを置き去りにして、ボールコントロールのままである。相手がボールを獲得できない状況（例：ボールが相手の上を「フリック」された場合）も、チャレンジとして記録される。
- Ball action carried out
　チャレンジの開始時に、チャレンジに関与するどのプレーヤーもボールコントロー ルをしておらず（例：空中戦のチャレンジ、ボールのファーストタッチに対するチャレンジ）、チャレンジ の終了時に1人のプレーヤーがボールの方向を決定している場合に適用される。パスに対してボールを競り合う場合など。
- Fouled
　レフェリーがファールを取った場合
- Opponent dispossessed
　ボールが奪取された場合
- Challenge during release of the ball
　ボールリリース中のチャレンジ。端的に言うとディフェンスされた状態でシュートやパスを行った場合。
チャレンジ中にシュートやボールのプレーが強制されたりブロックされたりした場合に適用される。チャレンジは、プレーされたボールまたはショットが、戦術的観点から防御側のプレーヤーがカバーしようとしている区域を通過した場合にのみ記録される。それ以外の場合は、チャレンジとして記録されない。
- Possession retained during challenge
　チャレンジに参加しているプレーヤーの1人が、チャレンジの開始時に一定のボールコントロールを持っていて、チャレンジに参加している相手プレーヤーからボールを奪う努力にもかかわらず、それを保持することができた場合に適用される。
オフェンスがディフェンスからボールを取られなかった場合？
