### ISSUE TITLE
📝DFL - Idea note

### ISSUE THREAD

**Issue by ryryrymyg** [ryryrymyg/kaggle_ell#94]
# アイデアノート
## Outline
[DFL - Bundesliga Data Shootout](https://www.kaggle.com/competitions/dfl-bundesliga-data-shootout/)のアイデアをぶら下げるノート
## Comments
まとまった形になったら別Issueに記載

**Comment by ryryrymyg** [comment]
- チームごとにプレイヤーをクラスタリングする
- ボールに近い人間をボール保持者とする
- EDAで各イベントを可視化する

**Comment by ryryrymyg** [comment]
【EDA】
◇仮説
イベントが起こる際(play or challenge)にボールと選手同士の位置(BBの位置)は限りなく近い
◇確認手法
フレーム毎にBBの位置を取得し、イベントが起こったときのBBの位置を取得し、ボールに最も近い二つを表示

**Comment by agatsssssma** [comment]
- 外部データを機械学習に用いる。yolov7の学習に外部データセットSoccerNetを使った事例あり　https://www.kaggle.com/code/its7171/yolov7-finetune-with-soccernet/notebook#SoccerNet-data-setting

**Comment by agatsssssma** [comment]
- 単純にyoloのbboxついた動画を学習させたら精度向上する？
